# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Default'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'GlobeFirstAPI.application.parent/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'


- task: Bash@3
  inputs:
    filePath: '/Users/nsurana/CICS_Setup/CI/build/TCI/deploy.exp'
    arguments: '/Users/nsurana/azureagent/_work/1/s/GlobeFirstAPI.application/target/GlobeFirstAPI.application_1.0.0.ear'